export enum FontSize {
  HEADING_1 = 34,
  HEADING_2 = 28,
  HEADING_3 = 23,
  HEADING_4 = 19,
  BODY_TEXT_MEDIUM = 15,
  BODY_TEXT_SMALL = 12,
  BODY_TEXT_VERY_SMALL = 10,
  BODY_TEXT_EXTRA_SMALL = 8,
}
