name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  backend-tests:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: MIIBOwIBAAJBAIK0Zss+Kc0hwJ9DhiS7tTLmTNx3sDJxgX+bzc8XmJscKeZyDKbtrR9qwP5UqrF2oMn596FfxDUsaURc44kobfECAwEAAQJAR9IxmgTym1Gsstc74vtyOiHqokryewV8D07h7KYeqTwrGPoqO5DzBBoUW43dV6n8oC1YBdjj6EPuiT/TqaNRQQIhAMPovmyUed7RPBRiTiWRnUMQW6UgFhdxJ2ZSSR1KOcedAiEAqsulq1k0UhgQEzDzt9duFDSOpzfykOtufD2j/XTEUWUCIQCRdXoN/KAQRKKrL+J+GoP9i2PAUvaUKTvrySToTnhgMQIhAJ+ML426fgK2UcXrs7AoAb/EPQJ+ZAz2sTZESr4I5x91AiBvRlMtGLiArdWNKgdLpvYU7O6F1L5cFR09QnD9jBQURQ==
    defaults:
      run:
        working-directory: back
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: '**/back/yarn.lock'

    - run: yarn
    - run: yarn build
    - run: yarn jest
    - run: | 
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE corposano' -uroot -proot
        mysql -e 'ALTER USER 'root'@'localhost' IDENTIFIED BY ""' -uroot -prootyarn test:inte
        yarn test:inte
    - run: yarn test:e2e
